// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backendApproval.Data;

#nullable disable

namespace backendApproval.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008015527_AddDatabaseGuards")]
    partial class AddDatabaseGuards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backendApproval.Domain.Entities.AccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("access_level");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_request_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<bool>("IsHighRisk")
                        .HasColumnType("boolean")
                        .HasColumnName("is_high_risk");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justification");

                    b.Property<Guid>("ManagerApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_approver_id");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("policy_version");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SystemOwnerApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_owner_approver_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_access_requests");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_access_requests_application_id");

                    b.HasIndex("PolicyVersion")
                        .HasDatabaseName("ix_access_requests_policy_version");

                    b.HasIndex("ManagerApproverId", "Status")
                        .HasDatabaseName("ix_access_requests_manager_status");

                    b.HasIndex("RequesterId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_access_requests_requester_client_request_id");

                    b.HasIndex("RequesterId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_access_requests_requester_created");

                    b.HasIndex("SystemOwnerApproverId", "Status")
                        .HasDatabaseName("ix_access_requests_system_owner_status");

                    b.ToTable("access_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_access_requests_access_level", "access_level IN ('Read', 'Admin')");

                            t.HasCheckConstraint("ck_access_requests_client_request_id_not_blank", "length(btrim(client_request_id)) > 0");

                            t.HasCheckConstraint("ck_access_requests_decided_at", "(status IN ('Approved', 'Rejected')) = (decided_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_access_requests_environment", "environment IN ('NonProduction', 'Production')");

                            t.HasCheckConstraint("ck_access_requests_justification_not_blank", "length(btrim(justification)) > 0");

                            t.HasCheckConstraint("ck_access_requests_manager_not_requester", "manager_approver_id <> requester_id");

                            t.HasCheckConstraint("ck_access_requests_owner_not_requester", "system_owner_approver_id IS NULL OR system_owner_approver_id <> requester_id");

                            t.HasCheckConstraint("ck_access_requests_rejection_reason", "(status = 'Rejected' AND rejection_reason IS NOT NULL AND length(btrim(rejection_reason)) > 0) OR (status <> 'Rejected' AND rejection_reason IS NULL)");

                            t.HasCheckConstraint("ck_access_requests_status", "status IN ('PendingManagerApproval', 'PendingSystemOwnerApproval', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("ck_access_requests_v1_high_risk_definition", "policy_version <> 'v1' OR is_high_risk = (environment = 'Production' OR access_level = 'Admin')");

                            t.HasCheckConstraint("ck_access_requests_v1_low_risk_no_owner_stage", "policy_version <> 'v1' OR NOT (status = 'PendingSystemOwnerApproval' AND NOT is_high_risk)");

                            t.HasCheckConstraint("ck_access_requests_v1_owner_assignment", "policy_version <> 'v1' OR (is_high_risk = (system_owner_approver_id IS NOT NULL))");

                            t.HasCheckConstraint("ck_access_requests_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SystemOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_owner_id");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_applications_code");

                    b.HasIndex("SystemOwnerId")
                        .HasDatabaseName("ix_applications_system_owner_id");

                    b.ToTable("applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "CRM",
                            Name = "CRM",
                            SystemOwnerId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "FINANCE_PORTAL",
                            Name = "Finance Portal",
                            SystemOwnerId = new Guid("00000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccessRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_request_id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("policy_version");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<int>("RequestVersion")
                        .HasColumnType("integer")
                        .HasColumnName("request_version");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_events_actor_id");

                    b.HasIndex("PolicyVersion")
                        .HasDatabaseName("ix_audit_events_policy_version");

                    b.HasIndex("AccessRequestId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_request_occurred");

                    b.HasIndex("AccessRequestId", "RequestVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_events_request_version");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_event_type", "event_type IN ('RequestCreated', 'ManagerApproved', 'ManagerRejected', 'SystemOwnerApproved', 'SystemOwnerRejected')");

                            t.HasCheckConstraint("ck_audit_events_reject_has_reason", "event_type NOT IN ('ManagerRejected', 'SystemOwnerRejected') OR (reason IS NOT NULL AND length(btrim(reason)) > 0)");
                        });
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.PolicyVersion", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.HasKey("Code")
                        .HasName("pk_policy_versions");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_policy_versions_single_active")
                        .HasFilter("is_active");

                    b.ToTable("policy_versions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "v1",
                            Description = "High-risk = Environment Production OR AccessLevel Admin. Semua request butuh Manager approval; high-risk lanjut ke System Owner approval.",
                            EffectiveFrom = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAuditor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_auditor");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_users_manager_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_lowercase", "email = lower(email)");

                            t.HasCheckConstraint("ck_users_not_own_manager", "manager_id IS NULL OR manager_id <> id");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            DisplayName = "Bob",
                            Email = "bob@example.local",
                            IsAuditor = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "Alice",
                            Email = "alice@example.local",
                            IsAuditor = false,
                            ManagerId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            DisplayName = "Carol",
                            Email = "carol@example.local",
                            IsAuditor = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            DisplayName = "Dana",
                            Email = "dana@example.local",
                            IsAuditor = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            DisplayName = "Erin",
                            Email = "erin@example.local",
                            IsAuditor = true
                        });
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.AccessRequest", b =>
                {
                    b.HasOne("backendApproval.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_requests_application");

                    b.HasOne("backendApproval.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_requests_manager");

                    b.HasOne("backendApproval.Domain.Entities.PolicyVersion", null)
                        .WithMany()
                        .HasForeignKey("PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_requests_policy_version");

                    b.HasOne("backendApproval.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_requests_requester");

                    b.HasOne("backendApproval.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SystemOwnerApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_requests_system_owner");

                    b.Navigation("Application");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.Application", b =>
                {
                    b.HasOne("backendApproval.Domain.Entities.User", "SystemOwner")
                        .WithMany()
                        .HasForeignKey("SystemOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_applications_system_owner");

                    b.Navigation("SystemOwner");
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("backendApproval.Domain.Entities.AccessRequest", null)
                        .WithMany("AuditEvents")
                        .HasForeignKey("AccessRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_access_request");

                    b.HasOne("backendApproval.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_actor");

                    b.HasOne("backendApproval.Domain.Entities.PolicyVersion", null)
                        .WithMany()
                        .HasForeignKey("PolicyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_policy_version");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.User", b =>
                {
                    b.HasOne("backendApproval.Domain.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("backendApproval.Domain.Entities.AccessRequest", b =>
                {
                    b.Navigation("AuditEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
